# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Package Release

on:
  release:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release 
    - name: Pack Nuget
      run: dotnet pack ./Avroify/Avroify/Avroify.csproj --no-build -o ./dist
    - name: Publish package
      run: dotnet nuget push ./dist --api-key ${{ secrets.NUGET_API_KEY }}
